/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Funciones.Citas;
import Funciones.Expedientes;
import Funciones.Pacientes;

/**
 *
 * @author Diony
 */
public class FrmPacientes extends javax.swing.JFrame {

    
    
    
    public FrmPacientes() {
        initComponents();       
         //Pacientes obpacientes = new Pacientes();      
         //obpacientes.MostrarPacienteConID(TBDatosDelPaciente, 3);
         //Expedientes obExpediente = new Expedientes();
         //obExpediente.MostarExpedienteIDPaciente(TablaExpedientes, 3);
    }
        //int IDnum = Integer.parseInt(PasarID.getText());
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PasarID = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TBDatosDelPaciente = new javax.swing.JTable();
        BTActualizar3 = new javax.swing.JButton();
        BTSalir3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaExpedientes = new javax.swing.JTable();
        BTActualizar1 = new javax.swing.JButton();
        BTSalir1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaCitas = new javax.swing.JTable();
        BTSalir2 = new javax.swing.JButton();
        BTActualizar2 = new javax.swing.JButton();

        PasarID.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apartado Pacientes");

        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        TBDatosDelPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(TBDatosDelPaciente);

        BTActualizar3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BTActualizar3.setText("Actualizar");
        BTActualizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTActualizar3ActionPerformed(evt);
            }
        });

        BTSalir3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BTSalir3.setForeground(new java.awt.Color(153, 51, 0));
        BTSalir3.setText("Salir");
        BTSalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSalir3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BTSalir3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTActualizar3)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTActualizar3)
                    .addComponent(BTSalir3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos del Paciente", jPanel4);

        TablaExpedientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TablaExpedientes);

        BTActualizar1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BTActualizar1.setText("Actualizar");
        BTActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTActualizar1ActionPerformed(evt);
            }
        });

        BTSalir1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BTSalir1.setForeground(new java.awt.Color(153, 0, 0));
        BTSalir1.setText("Salir");
        BTSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BTSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTActualizar1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTSalir1)
                    .addComponent(BTActualizar1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Expediente", jPanel2);

        TablaCitas.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        TablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TablaCitas);

        BTSalir2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BTSalir2.setForeground(new java.awt.Color(153, 51, 0));
        BTSalir2.setText("Salir");
        BTSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSalir2ActionPerformed(evt);
            }
        });

        BTActualizar2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BTActualizar2.setText("Actualizar");
        BTActualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTActualizar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTActualizar2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTSalir2)
                    .addComponent(BTActualizar2))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Citas", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTActualizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTActualizar3ActionPerformed
        Pacientes obpacientes = new Pacientes();    
        int IDnum = Integer.parseInt(PasarID.getText());
        obpacientes.MostrarPacienteConID(TBDatosDelPaciente, IDnum);
        
    }//GEN-LAST:event_BTActualizar3ActionPerformed

    private void BTActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTActualizar1ActionPerformed
         Expedientes obExpediente = new Expedientes();
         int IDnum = Integer.parseInt(PasarID.getText());
         obExpediente.MostarExpedienteIDPaciente(TablaExpedientes, IDnum);
    }//GEN-LAST:event_BTActualizar1ActionPerformed

    private void BTSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSalir3ActionPerformed
        FrmPrincipal pepe = new FrmPrincipal();
        pepe.setVisible(true);
        this.dispose();;
    }//GEN-LAST:event_BTSalir3ActionPerformed

    private void BTSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSalir1ActionPerformed
        FrmPrincipal pepe = new FrmPrincipal();
        pepe.setVisible(true);
        this.dispose();;
    }//GEN-LAST:event_BTSalir1ActionPerformed

    private void BTSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSalir2ActionPerformed
        FrmPrincipal pepe = new FrmPrincipal();
        pepe.setVisible(true);
        this.dispose();;
    }//GEN-LAST:event_BTSalir2ActionPerformed

    private void BTActualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTActualizar2ActionPerformed
        Citas obExpediente = new Citas();
        int IDnum = Integer.parseInt(PasarID.getText());
        obExpediente.MostrarCitaConID(TablaCitas, IDnum);
    }//GEN-LAST:event_BTActualizar2ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTActualizar1;
    private javax.swing.JButton BTActualizar2;
    private javax.swing.JButton BTActualizar3;
    private javax.swing.JButton BTSalir1;
    private javax.swing.JButton BTSalir2;
    private javax.swing.JButton BTSalir3;
    public static javax.swing.JTextField PasarID;
    private javax.swing.JTable TBDatosDelPaciente;
    private javax.swing.JTable TablaCitas;
    private javax.swing.JTable TablaExpedientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
